---
title: Drama Queen
timezone: America/Bogota
collections:
  cosas:
    title: Cosas
    output: true
  up-characters:
    title: Personajes abajo
    output: true
  down-characters:
    title: Personajes arriba
    output: true
  platforms:
    title: Plataformas
    output: true
  posts:
    title: Posts
    output: true
  queens:
    title: Queens
    output: true
  videos:
    title: Video
    output: true  
  uploads:
    title: Uploads
    output: true
subtitle: Making Stories
email: camila.bruges@gmail.com
description: Descripci√≥n pendiente
image:
baseurl: 
url: 
theme: minima
github: dramaqueenw
x: dramaqueen_ms
instagram: dramaqueenstories
vimeo: dramaqueenstories
plugins:
- jekyll-feed
- jekyll-seo-tag
